### ISSUE TITLE
还有以前的文件吗  最新的我连系统都进不去

### ISSUE THREAD

**Issue by lyydhy** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#12]
进不去啊 发行版里面两个版本我都试过了 进不去

**Comment by lyydhy** [comment]
![QQ图片20200510134310](https://user-images.githubusercontent.com/19465770/81491748-4067a100-92c4-11ea-8ec7-1af14a23090a.jpg)

**Comment by andreacoradi** [comment]
Try this:

RebuildAppleMemoryMap=False

SetupVitualMap=True

**Comment by lyydhy** [comment]
可以了 谢谢

**Comment by lyydhy** [comment]
你好 大佬 后面有打算支持 最新的 macOS Big Sur吗？



在 2020-05-11 03:23:26，"Andrea Coradi" <notifications@github.com> 写道：

Try this:

RebuildAppleMemoryMap=False

SetupVitualMap=True
