### ISSUE TITLE
这款matebook现在值得入手吗？

### ISSUE THREAD

**Issue by edamame43** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#13]
打算新入手一个黑苹果比较完美的本本，请问下这款除了显卡和Wi-Fi外其它全部正常么？有没什么小问题比如唤醒后鼠标键盘滞后？或者哪一款本黑得更完美一点？谢谢

**Comment by wentailaiii** [comment]
感觉这款不是很合适黑苹果 我就是用的这款matebookd

**Comment by edamame43** [comment]
> 感觉这款不是很合适黑苹果 我就是用的这款matebookd

为啥？哪些方面不适合？

**Comment by Zero-zer0** [comment]
在2020年，从一台PC产品的角度来看，Matebook D 2018不是一款合格的笔记本：低色域屏幕，15w功耗墙（锁死），糟糕的续航，没有背光键盘、指纹、Type-C，糟糕的外壳做工，与性能不匹配的机身重量...即使是从发布的时候来看，它仍然不值得购买。

当让，如果你能以十分低廉的价格（3000 RMB以下的i5-8250U版）买到，依然不值得。你能收到同价位品牌的荣耀Magicbook 2018，弥补了键盘背光、Type-C、续航等痛点。拿到手换屏+换网卡就能拥有相对不错的黑苹果体验（除了指纹和独显，以及要更换的网卡之外，其他与Matebook D 2018没有区别）。

如果你想在2020年拥有较好的macOS体验，还是推荐购买一台MacBook XD。
即使是黑苹果，华为/荣耀的新机器也不再值得考虑。

**Comment by edamame43** [comment]
我主要得考虑是尽量能实现黑苹果的正常运行，因为除了这款，我只能在联想的昭阳系列和华硕的商用系列选择（单位），这两个系列几乎都找不到黑苹果的支持（得自己试），只有联想的一款有可惜是12寸，跑遍pcbeta，insanelymac和tonyx86都无，你说的这些缺点的话，大部分我可以接受，15w功耗墙是指什么？我比较在乎的是散热怎么样，比如同时跑Xcode，eclipse这些，电池我向来都没什么期待。。
