### ISSUE TITLE
CFG Lock 还是被锁的，求大佬帮助

### ISSUE THREAD

**Issue by hjames1** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#15]
大佬，感谢您分享的EFI，用你的最新版的EFI进入系统后，
用hackintool查看了一下CFG lock的状态发现：
CFG Lock............................. : 1 (MSR locked until next reset)
求大佬帮助，感谢！

**Comment by Zero-zer0** [comment]
该机器的CFG Lock**即使不解锁也能正常使用**，OpenCore并没有自动解锁CFG Lock的功能

你可以使用`H2OUVE`或者`ru.efi`进行解锁，具体方法在远景论坛上非常多，自行研究。

**Comment by hjames1** [comment]
感谢大佬回复！
