### ISSUE TITLE
声音有时候没得

### ISSUE THREAD

**Issue by lyydhy** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#4]
用着用着 有时候声音都没得了  然后就需要重启才行

**Comment by lyydhy** [comment]
大佬有这种情况吗？因为经常不关机 所以会遇到

**Comment by Zero-zer0** [comment]
你可以尝试使用[ALCPlugFix](https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore/blob/master/ALCPlugFix.zip)来解决这个问题。另外，保证不要在系统的其他目录安装一些奇奇怪怪的kext。
