### ISSUE TITLE
大佬，我试着在Kernel里加入1820A的蓝牙驱动，能够发现设备，但是无法连接设备，请问怎么解决？

### ISSUE THREAD

**Issue by Dreamer-YanYan** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#5]
我的网卡是1820A的00jt494版本，用兵哥提供的驱动，您的OC引导下蓝牙能够识别设备，但是无法连接，使用了clover引导，可以驱动，能正常使用。谢谢您回复。

**Comment by Zero-zer0** [comment]
1. OpenCore与Clover的逻辑不同。在Clover中，加入ACPI表、kexts只需要放文件就行。但是在OpenCore中，这还不够，你需要在`config.plist`的`Kernel-Add`中填写kext的相关信息，同时还需要注意它们的顺序。
2. 至于使用`DW1820A`/ `00JT493`/ `00JT494` ,相对更加稳妥的方式是把`BrcmPatchRAM`相关的kexts放在`/Library/Extensions`目录下，并使用`BrcmPatchRAM3`+`BrcmFirmwareRepo`+`BrcmBluetoothInjector`三件套。这样就可以不需要修改OpenCore引导的同时，获得更稳定的体验。可以在[BrcmPatchRAM](https://github.com/acidanthera/BrcmPatchRAM/releases)下载。</br>当然，黑果小兵修改的“稳定版”“三件套”同样可以使用，其中的`BrcmPatchRAM2`是早期修改过的版本，同样支持macOS 10.15及以上的系统，个人推荐的使用方法同上。

**Comment by Dreamer-YanYan** [comment]
&nbsp;谢谢大佬，蓝牙好使了，再次感谢回复！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zero-zer0"<notifications@github.com&gt;; 
发送时间: 2020年3月13日(星期五) 晚上7:55
收件人: "Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore"<Matebook_D_2018_Hackintosh_OpenCore@noreply.github.com&gt;; 
抄送: "1141993680"<1141993680@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore] 大佬，我试着在Kernel里加入1820A的蓝牙驱动，能够发现设备，但是无法连接设备，请问怎么解决？ (#5)





  
OpenCore与Clover的逻辑不同。在Clover中，加入ACPI表、kexts只需要放文件就行。但是在OpenCore中，这还不够，你需要在config.plist的Kernel-Add中填写kext的相关信息，同时还需要注意它们的顺序。
 
至于使用DW1820A/ 00JT493/ 00JT494 ,相对更加稳妥的方式是把BrcmPatchRAM相关的kexts放在/Library/Extensions目录下，并使用BrcmPatchRAM3+BrcmFirmwareRepo+BrcmBluetoothInjector三件套。这样就可以不需要修改OpenCore引导的同时，获得更稳定的体验。可以在BrcmPatchRAM下载。
当然，黑果小兵修改的“稳定版”“三件套”同样可以使用，其中的BrcmPatchRAM2是早期修改过的版本，同样支持macOS 10.15及以上的系统，个人推荐的使用方法同上。

**Comment by Dreamer-YanYan** [comment]
大佬，又遇到了一个问题，睡眠唤醒后，蓝牙能连接鼠标，但是比较卡，音响直接连不上。
/Library/Extensions目录下放的是BrcmFirmwareData.kext，BrcmPatchRAM2.kext
oc/kexts目录下放的是BrcmBluetoothInjector.kext，BrcmFirmwareRepo.kext，BrcmPatchRAM3.kext
config里的Kernel-Add中，21是BrcmBluetoothInjector.kext，22是BrcmFirmwareRepo.kext，23是BrcmPatchRAM3.kext，这些都是从https://github.com/acidanthera/BrcmPatchRAM/releases这里下载的。
还有就是睡眠唤醒后，没有声音，睡眠之前是正常的。ID是21，
MacBook ~ % ioreg -l | grep layout-id
    | |   | |   "layout-id" = <07000000>
    | |   | |   "alc-layout-id" = <15000000>
    | |   |             | |   "IOAudioEngineDeviceDescription" = {"num-internal-mics"=1,"driver digital input gain"=0,"layout-id"=7,"post-processing input gain"=25,"VP-pregain"=25}
    | |   |             | |   "IOAudioEngineDeviceDescription" = {"num-internal-mics"=0,"driver digital input gain"=0,"layout-id"=7,"post-processing input gain"=25,"VP-pregain"=25}

MacBook ~ % kextstat | grep AppleALC                                                                                                                 

   45    0 0xffffff7f84505000 0x136000   0x136000   as.vit9696.AppleALC (1.4.7) 04E7C377-78E7-3FC9-8DE4-2FADC30553B3 <41 13 8 6 5 3 2 1>

**Comment by Zero-zer0** [comment]
1. 首先，保证所有蓝牙驱动放在`/Library/Extensions`下，或者在使用OpenCore在开机是注入，两种方式**只能二选一**。另外，保证三个kext**版本一致**。在bootloader和系统目录同时放作用相同而版本不同的kext会导致严重的冲突问题。</br>
另外，可以在`boot-args`下添加`bpr_probedelay=100` `bpr_initialdelay=300` `bpr_postresetdelay=300` 三个参数来尝试解决唤醒后蓝牙不好使的问题，方法来源于黑果小兵。如果你对蓝牙稳定性有比较高的需求，更推荐使用`BCM94360CS2`这一类拆机卡。当然，在蓝牙信号上还是拉垮。

2. 至于唤醒后没有声音，可以尝试使用[ALCPlugFix](https://github.com/Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore/blob/master/ALCPlugFix.zip) 来解决，欢迎提出反馈，我用这个一直没有出过什么问题。</br>
如果发现了其他声卡问题，比如切换问题（应该没有）还可以尝试使用[ComboJack](https://github.com/Heporis/ComboJack)来解决，在华为/荣耀的一些机器上，这个有效果，但是我还没有测试过。我日常都是用USB DAC的XD。

**Comment by Dreamer-YanYan** [comment]
谢谢，谢谢，我试试看，有问题再请教您。感谢回复。🙏



---原始邮件---
发件人: "Zero-zer0"<notifications@github.com&gt;
发送时间: 2020年3月13日(星期五) 晚上11:54
收件人: "Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore"<Matebook_D_2018_Hackintosh_OpenCore@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"Dreamer-YanYan"<1141993680@qq.com&gt;;
主题: Re: [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore] 大佬，我试着在Kernel里加入1820A的蓝牙驱动，能够发现设备，但是无法连接设备，请问怎么解决？ (#5)




  
 
首先，保证所有蓝牙驱动放在/Library/Extensions下，或者在使用OpenCore在开机是注入，两种方式只能二选一。另外，保证三个kext版本一致。在bootloader和系统目录同时放作用相同而版本不同的kext会导致严重的冲突问题。

 另外，可以在boot-args下添加bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300 三个参数来尝试解决唤醒后蓝牙不好使的问题，方法来源于黑果小兵。如果你对蓝牙稳定性有比较高的需求，更推荐使用BCM94360CS2这一类拆机卡。当然，在蓝牙信号上还是拉垮。
 

 
至于唤醒后没有声音，可以尝试使用ALCPlugFix 来解决，欢迎提出反馈，我用这个一直没有出过什么问题。

 如果发现了其他声卡问题，比如切换问题（应该没有）还可以尝试使用ComboJack来解决，在华为/荣耀的一些机器上，这个有效果，但是我还没有测试过。我日常都是用USB DAC的XD。
