### ISSUE TITLE
安装了alcplugfix 报错

### ISSUE THREAD

**Issue by lyydhy** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#6]
![IMG20200315150009](https://user-images.githubusercontent.com/19465770/76697300-98bd6080-66d0-11ea-9869-21f357e49e79.jpg)
安装了这个后 就报错 我重启了好几次 开机了 但是触摸板又不能用了  大佬 怎么搞  我都不敢关机了

**Comment by Zero-zer0** [comment]
1. 出现这种状况的原因之一，可能是在重建缓存后，没有正确关机，缓存损坏导致的。

2. 尝试进入`recovery`进行以下操作（至于如何进入，可以尝试`Clover`）

> 2.cd "/Volumes/Macintosh HD"
> 这里Macintosh HD是我的磁盘名，你输入你的磁盘名就行
> 这里有一个很方便的方法检测一下你输入的是否正确，比如这里写到Macin的时候按Tab键直接出来Macintosh HD，如果没有出现，你就应该回到前提那里重来了

> 3.touch System/Library/Extensions
> 这里也都是顺序执行，检测方法也是按Tab键看是否直接出来提示

> 4.kextcache -prelinked-kernel System/Library/Caches/com.apple.kext.caches/Startup/kernelcache -K System/Library/Kernels/kernel System/Library/Extensions

> ~~执行第1步的时候，屏幕显示kext-dev-mode=1~~，执行2、3布的时候没有提示，执行第4步的时候就开始自动处理了，等一段时间（不超过十分钟），屏幕不再输出的时候重启就可以了

以上内容来自[这里](
