### ISSUE TITLE
安装卡在第一次看到鼠标这个界面

### ISSUE THREAD

**Issue by bss03arg** [Zero-zer0/Matebook_D_2018_Hackintosh_OpenCore#9]
HI

我用的是1802a网卡，我用你的OC EFI，然后替换掉macOS Catalina 10.15.3 19D76 正式版 iso中的EFI，安装一直卡这里，没有提示信息。

是不是因为网卡的问题呢？

可否详细说明一下你使用的iso，非常感谢！

![image](https://user-images.githubusercontent.com/39295782/77246037-4e9f2680-6c5e-11ea-91bb-8f90093eb14d.png)

**Comment by Zero-zer0** [comment]
1. `DW1820A`的确会导致一些开机卡死的问题。根据我经手的几张`DW1820A`的使用体验来看，在系统升级/安装的过程中最好在BIOS中禁用网卡设备，不然很容易卡死/无故重启。

2. 镜像的来源很多，使用黑果小兵的10.15.x的都没有问题。我使用的是Recoery+Wi-Fi在线安装。

3. 请在config的`NVRAM-Add-7C436110-AB2A-4BBB-A880-FE41995C9F82-boot-args`下添加`-v`,`debug=0x100`等参数在屏幕上输出日志进行排错。

**Comment by bss03arg** [comment]
非常感谢你的回复！！！我再试试！

Best Regards

Product Development Department
Chun Cui
Email: cuichun@inateck.com
F&M Technology GmbH
Add: Fraunhofer Straße 7, 04178 Leipzig, Germany
Tel.: +49-341-51998410
Fax: +49-341-51998413
Website: www.inateck.com


Zero-zer0 <notifications@github.com> 于2020年3月22日周日 下午9:46写道：
